name: Java CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Give Maven Wrapper Permission
        run: chmod +x app/app/mvnw

      - name: Build App
        run: |
          cd app/app
          ./mvnw clean verify

      - name: SonarCloud Scan
        run: |
          cd app/app
          ./mvnw sonar:sonar \
          -Dsonar.projectKey=vishnuteja0217_enterprise-devops-project \
          -Dsonar.organization=vishnuteja0217 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}