name: Java CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app/app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Give Permission to Maven Wrapper
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Build Docker Image
        run: docker build -t enterprise-app .